ignore:
  # picomatch
  - vulnerability: GHSA-c2c7-rcm5-vvqj
  # flatted
  - vulnerability: GHSA-rf6f-7fwh-wjgh
  # minimatch
  - vulnerability: GHSA-3ppc-4f35-3m26
  - vulnerability: GHSA-7r86-cg39-jmmj
  - vulnerability: GHSA-23c5-xmqv-rm74
  - vulnerability: GHSA-25h7-pfq9-p65f
