vulnerabilities:
  - id: CVE-2025-64756
    statement: downstream dependency for glob - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-23745
    statement: downstream dependency for tar - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-23950
    statement: downstream dependency for tar - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-24842
    statement: downstream dependency for tar - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-25547
    statement: downstream dependency for @isaacs/brace-expansion - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-0775
    statement: downstream dependency for npmcli - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-24049
    statement: downstream dependency for wheel - waiting for new python release
    expired_at: 2026-06-01
  - id: CVE-2025-47907
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2025-58183
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2025-61729
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2025-61726
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2025-61728
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2025-61730
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2025-68121
    statement: downstream dependency for asdf/go - waiting for new asdf release
    expired_at: 2026-06-01
  - id: CVE-2026-26278
    statement: fast-xml-parser node module
    expired_at: 2026-06-01
  - id: CVE-2026-26996
    statement: minimatch node module
    expired_at: 2026-06-01
  - id: CCVE-2026-26960
    statement: tar node module
    expired_at: 2026-06-01
