name: merge to main workflow

on:
  push:
    branches: [main]

permissions: {}
jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@c8f899f30a6a726859b0277faa73cd9ff7f4de20
    with:
      verify_published_from_main_image: true
    permissions:
      attestations: read
      contents: read
      packages: read
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@8399c1f015c1304e40771cbd8ccc24c7ed48fdbc
    needs: [get_config_values]
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      run_docker_scan: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    needs: [quality_checks, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@c8f899f30a6a726859b0277faa73cd9ff7f4de20
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      dry_run: true
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      publish_packages: packages/cdkConstructs,packages/deploymentUtils
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}

  package_npm_code:
    needs: [quality_checks, get_config_values]
    uses: ./.github/workflows/package_npm_code.yml
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
