name: release workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3"

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@b0172dbdb3af4ae232873106553c316d79d784fc
    with:
      verify_published_from_main_image: true
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@352f15f692c23b18f67215ad858f27b06a878717
    needs: [get_config_values]
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      run_docker_scan: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    needs: [quality_checks, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@352f15f692c23b18f67215ad858f27b06a878717
    with:
      dry_run: false
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      publish_packages: packages/cdkConstructs,packages/deploymentUtils
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}
    secrets: inherit
