name: release workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3"

permissions: {}
jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@f747b664d45e3a554d5ab72af509ab8e14fe84aa
    with:
      verify_published_from_main_image: true
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@f747b664d45e3a554d5ab72af509ab8e14fe84aa
    needs: [get_config_values]
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      run_docker_scan: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    needs: [quality_checks, get_config_values]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@f747b664d45e3a554d5ab72af509ab8e14fe84aa
    with:
      dry_run: false
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: main
      publish_packages: packages/cdkConstructs,packages/deploymentUtils
      tag_format: ${{ needs.get_config_values.outputs.tag_format }}
